[user]
name = "George Czabania"
email = "1140167+stayradiated@users.noreply.github.com"

[template-aliases]
'format_short_signature(signature)' = 'signature.name()'

[ui]
pager = ["delta", "--diff-so-fancy"]
diff-formatter = ":git"

[remotes.origin]
auto-track-bookmarks = "glob:george/*"
